### ISSUE TITLE
Email is not returned by first call

### ISSUE THREAD

**Issue by jthake** [matthiaseinig/WordAddin-Office365UnifiedAPI-ADALJS-Demo#1]
In Home.js line 26 
var email = result.value;

The value is an empty string.

authContext._user.userName is where the email actually is.

**Comment by jthake** [comment]
Changing to var email = authContext._user.userName; fixes problem

**Comment by matthiaseinig** [comment]
Thanks for the easy fix. Worked well 4 months ago, but that happens when using a beta API ;)
